# example netlify.toml
[build]
  command = "astro build"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[[plugins]]
  package = "netlify-plugin-inline-source"
[[plugins]]
  package = "netlify-plugin-minify-html"
[[plugins]]
  package = "@netlify/plugin-sitemap"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[functions]
  directory = "src/functions"

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true