# example netlify.toml
[build]
  command = "astro build"
  # functions = "netlify/functions"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-inline-source"
[[plugins]]
  package = "netlify-plugin-minify-html"
[[plugins]]
  package = "@netlify/plugin-sitemap"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"