# example netlify.toml
[build]
  command = "astro build"
  # functions = "netlify/functions"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[[redirects]]
  from = "/proxy/*"
  to = ":splat"
  status = 200
  force = true

[[plugins]]
  package = "netlify-plugin-inline-source"
[[plugins]]
  package = "netlify-plugin-minify-html"
[[plugins]]
  package = "@netlify/plugin-sitemap"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"